//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubsetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.News = new HashSet<News>();
            this.sessions = new HashSet<sessions>();
        }
    
        public string course_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<sessions> sessions { get; set; }
    }
}
