//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubsetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string course_id { get; set; }
        public System.DateTime time_posted { get; set; }
        public string text { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
