//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubsetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessions
    {
        public int id { get; set; }
        public string course_id { get; set; }
        public string day { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public string type { get; set; }
        public string instructor_id { get; set; }
        public string cohort { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
